# Generated by Django 3.2.9 on 2021-11-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20211124_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglist',
            name='dropped',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='purchased',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='read',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='unread',
            field=models.TextField(default='[]'),
        ),
    ]
